# Generated by Django 4.2.7 on 2023-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
