# Generated by Django 4.2.7 on 2023-12-01 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage_pass_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
