# Generated by Django 4.2.7 on 2023-12-02 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_percentage_pass_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage_pass_rate',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
